<a href="https://colab.research.google.com/github/pradeeprajeswari/Deep-Learning-with-PyTorch/blob/main/02_PyTorch_Basics_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Basics Exercises
For these exercises we'll create a tensor and perform several operations on it.

<div class="alert alert-danger" style="margin: 10px"><strong>IMPORTANT NOTE!</strong> Make sure you don't run the cells directly above the example output shown, <br>otherwise you will end up writing over the example output!</div>

### 1. Perform standard imports
Import torch and NumPy

In [1]:
# CODE HERE

import torch
import numpy as np

### 2. Set the random seed for NumPy and PyTorch both to "42"
This allows us to share the same "random" results.

In [2]:
# CODE HERE
np.random.seed(42)
torch.manual_seed(42)


### 3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive)

In [3]:
# CODE HERE
arr=np.random.randint(0,5,size=6)
print(arr)


[3 4 2 4 4 1]


In [ ]:
# DON'T WRITE HERE

[3 4 2 4 4 1]


### 4. Create a tensor "x" from the array above

In [5]:
# CODE HERE
x=torch.tensor(arr)
print(x)


tensor([3, 4, 2, 4, 4, 1])


In [ ]:
# DON'T WRITE HERE

tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


### 5. Change the dtype of x from 'int32' to 'int64'
Note: 'int64' is also called 'LongTensor'

In [6]:
# CODE HERE
x=x.to(torch.int64)
x=x.long()
print(x.dtype)

torch.int64


In [ ]:
# DON'T WRITE HERE

torch.LongTensor


### 6. Reshape x into a 3x2 tensor
There are several ways to do this.

In [7]:
# CODE HERE
x_reshaped=x.view(3, 2)
print(x_reshaped)



tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [ ]:
# DON'T WRITE HERE

tensor([[3, 4],
        [2, 4],
        [4, 1]])


### 7. Return the right-hand column of tensor x

In [8]:
# CODE HERE
right_column=x_reshaped[:, -1]
print(right_column)


tensor([4, 4, 1])


In [ ]:
# DON'T WRITE HERE

tensor([[4],
        [4],
        [1]])


### 8. Without changing x, return a tensor of square values of x
There are several ways to do this.

In [9]:
# CODE HERE

x_squared=x ** 2
squared_x=torch.pow(x, 2)
print(squared_x)

tensor([ 9, 16,  4, 16, 16,  1])


In [ ]:
# DON'T WRITE HERE

tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


### 9. Create a tensor "y" with the same number of elements as x, that can be matrix-multiplied with x
Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive).<br>
Think about what shape it should have to permit matrix multiplication.

In [10]:
# CODE HERE

y=torch.randint(0, 5, (2, 3))
print(y)

tensor([[2, 2, 1],
        [4, 1, 0]])


In [ ]:
# DON'T WRITE HERE

tensor([[2, 2, 1],
        [4, 1, 0]])


### 10. Find the matrix product of x and y

In [12]:
# CODE HERE

result=torch.mm(x_reshaped, y)
print("reshaped:\n", x_reshaped)
print("y:\n", y)
print("Matrix multiplication result:\n", result)

reshaped:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])
y:
 tensor([[2, 2, 1],
        [4, 1, 0]])
Matrix multiplication result:
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


In [ ]:
# DON'T WRITE HERE

tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])


## Great job!